###
GET http://localhost:8080/api/employees

###
GET http://localhost:8080/api/employees/1

###
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "John Doe"
}

### Validation
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": ""
}

###
PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "id": 1,
  "name": "John Doe XXX"
}

###
DELETE http://localhost:8080/api/employees/2

###
GET http://localhost:8080/api/counter